name: Daily Weather Bot

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update-weather:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        persist-credentials: true

    - name: Set up API key
      run: echo "API_KEY=${{ secrets.OPENWEATHER_API_KEY }}" > .env

    - name: Run weather script
      run: |
        chmod +x weather.sh
        ./weather.sh

    - name: Commit and push changes
      run: |
        git config user.email "github-actions@github.com"
        git config user.name  "github-actions"
        git add weather.txt
        git commit -m "Daily weather update" || echo "No changes to commit"
        git push



